services:
  - type: web
    name: khata-book-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: khatabook  # <-- यहाँ अपने PostgreSQL डेटाबेस का सही नाम डालें
          property: internalDatabaseUrl
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.4

databases:
  - name: khatabook # <-- यहाँ भी अपने PostgreSQL डेटाबेस का सही नाम डालें
    plan: free
